spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wordweb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


  mvc:
    #配置它以后移动html页面就不用改路径了！
    static-path-pattern: /static/**    #静态资源的请求方式
  resources:
    static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录

  mail:
    host: smtp.qq.com
    username: 13554092267@qq.com
    password: bpqfznihusisffgd
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  thymeleaf:
    cache: false
    check-template-location: on
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.example.pojo
  configuration:
    map-underscore-to-camel-case: on #采用驼峰标识


# pagehelper分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8081

#加入之后程序报错
##解决Maximum upload size exceeded
#  # 单个文件大小为5MB
#  spring.servlet.multipart.max-file-size = 5MB
#
#  # 总上传的数据大小5MB
#  spring.servlet.multipart.max-request-size = 5MB
